version: "2"
services:
  app:
    build:
      context: .
    restart: always
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_TASK_DB=${NOTION_TASK_DB}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_OWNER_ID=${TELEGRAM_OWNER_ID}
      - TELEGRAM_ALLOW_IDS=${TELEGRAM_ALLOW_IDS}
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
